require("core.keymap.helper")

inoremap("jj", "<Esc>")
inoremap("j ", "j")
inoremap('""', '""<Left>')
inoremap("''", "''<Left>")
inoremap("(", "()<Left>")
inoremap("()", "()")
inoremap("(;", "();<Left><Left>")
inoremap("[", "[]<Left>")
inoremap("[]", "[]")
inoremap("{", "{}<Left>")
inoremap("{}", "{}")
inoremap("{<CR>", "{<CR>}<ESC>O")
inoremap("{;<CR>", "{<CR>};<ESC>O")

inoremap(",", ",<c-g>u")
inoremap(".", ".<c-g>u")
inoremap("!", "!<c-g>u")
inoremap("?", "?<c-g>u")
inoremap(":", ":<c-g>u")
inoremap(";", ";<c-g>u")
inoremap("=", "=<c-g>u")
inoremap("'", "'<c-g>u")
inoremap('"', '"<c-g>u')
inoremap("|", "|<c-g>u")
inoremap("<Space>", "<Space><c-g>u")
inoremap("<CR>", "<CR><c-g>u")

nnoremap("tt", ":10sp|:terminal<CR>", {silent = true})
nnoremap("<leader>d", '"0d')
nnoremap("<leader>x", '"0x')
nnoremap("<leader>c", '"0c')
--nnoremap("<leader>s", '"0s')
nnoremap("<leader>D", '"0D')
nnoremap("<leader>X", '"0X')
nnoremap("<leader>C", '"0C')
nnoremap("<leader>S", '"0S')
nnoremap("p", '"0p')
nnoremap("P", '"0P')
nnoremap("<leader>y", '"+y')
nnoremap("<leader>Y", '"+y$')
nnoremap("Y", "y$")
nnoremap("oo", "o<ESC>")
nnoremap("OO", "O<ESC>")
nnoremap('""', 'ciw""<Esc>P')
nnoremap("''", "ciw''<Esc>P")
nnoremap("((", "ciw()<Esc>PF(")
nnoremap("))", "ciw()<Esc>P")
nnoremap("{{", "ciw{}<Esc>PF{")
nnoremap("}}", "ciw{}<Esc>P")
nnoremap("[[", "ciw[]<Esc>PF[")
nnoremap("]]", "ciw[]<Esc>P")
nnoremap("<leader>**", "ciw**<Esc>P")
nnoremap("``", "ciw``<Esc>P")
nnoremap('<leader>""', 'ciw\\"\\"<Esc><Left>P')
nnoremap("<leader>''", "ciw\\'\\'<Esc><Left>P")
nnoremap("<leader>s", ":%s/")
nnoremap("<c-J>", "i<CR><ESC>")

vnoremap('<leader>d', '"0d')
vnoremap('<leader>x', '"0x')
vnoremap('<leader>c', '"0c')
--vnoremap <leader>s "0s
vnoremap("<leader>s", ":s/")
vnoremap('<leader>D', '"0D')
vnoremap('<leader>X', '"0X')
vnoremap('<leader>C', '"0C')
vnoremap('<leader>S', '"0S')
vnoremap('p', '"0p')
vnoremap('P', '"0P')
vnoremap("J", ":m '>+1<CR>gv=gv", { silent = true })
vnoremap("K", ":m '<-2<CR>gv=gv", { silent = true })
vnoremap('""', 'c""<Esc>P')
vnoremap("''", "c''<Esc>P")
vnoremap("((", "c()<Esc>PF(")
vnoremap("))", "c()<Esc>P")
vnoremap("{{", "c{}<Esc>PF{")
vnoremap("}}", "c{}<Esc>P")
vnoremap("[[", "c[]<Esc>PF[")
vnoremap("]]", "c[]<Esc>P")
vnoremap("<leader>**", "c**<Esc>P")
vnoremap("``", "c``<Esc>P")

tnoremap("<Esc>", "<C-\\><C-n>")
tnoremap("<Esc><Esc>", "<C-\\><C-n>:bd!<CR>", { silent = true })
tnoremap("<C-W>", "<C-\\><C-n><C-W>")
